# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'myStoryly' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Storyly', "2.2.1"

  # Pods for myStoryly

  target 'myStorylyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myStorylyUITests' do
    # Pods for testing
  end

end
