# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Preview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Storyly'

  # Pods for Preview

  target 'PreviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PreviewUITests' do
    # Pods for testing
  end

end
