# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'sampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Storyly', '1.33.0'

  # Pods for sampleApp

  target 'sampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleAppUITests' do
    # Pods for testing
  end

end
